<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ── PREMIUM (category_id: 1) ────────────────────────────────────
            [
                'name'           => 'Beras Putih AJP',
                'category_id'    => 1,
                'description'    => 'Beras Premium berkualitas tinggi dengan tekstur pulen dan aroma wangi alami.',
                'price'          => 660000,
                'weight_kg'      => 50,
                'stock'          => 120,
                'min_order'      => 1,
                'max_order'      => 20,
                'total_sold'     => 0,
                'avg_rating'     => 4.8,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('ajp.png'),
            ],
            [
                'name'           => 'Beras Putih Bima',
                'category_id'    => 1,
                'description'    => 'Beras Premium asal Jawa Tengah, butir panjang dengan aroma wangi khas.',
                'price'          => 675000,
                'weight_kg'      => 10,
                'stock'          => 90,
                'min_order'      => 1,
                'max_order'      => 20,
                'total_sold'     => 0,
                'avg_rating'     => 4.9,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('bima.png'),
            ],
            [
                'name'           => 'Beras Putih Cap BK ',
                'category_id'    => 1,
                'description'    => 'Beras cap bk , tekstur nasi lembut dan harum.',
                'price'          => 670000,
                'weight_kg'      => 10,
                'stock'          => 60,
                'min_order'      => 1,
                'max_order'      => 15,
                'total_sold'     => 0,
                'avg_rating'     => 4.9,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('bk-Kupu-kupu.png'),
            ],
            [
                'name'           => 'Beras Putih Cap Bunga Mawar',
                'category_id'    => 1,
                'description'    => 'Beras Putih tanpa pestisida, ditanam secara alami.',
                'price'          => 360000,
                'weight_kg'      => 25,
                'stock'          => 40,
                'min_order'      => 1,
                'max_order'      => 10,
                'total_sold'     => 0,
                'avg_rating'     => 5.0,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('bunga.png'),
            ],
            [
                'name'           => 'Beras ketan Putih cap mikky mouse ',
                'category_id'    => 1,
                'description'    => 'Beras Ketan Premium, cocok untuk kue tradisional dan makanan khas Indonesia.',
                'price'          => 550000,
                'weight_kg'      => 25,
                'stock'          => 200,
                'min_order'      => 1,
                'max_order'      => 30,
                'total_sold'     => 0,
                'avg_rating'     => 4.6,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('Ketan-mikkymouse.png'),
            ],
            [
                'name'           => 'Beras ketan  Putih Cap SI ',
                'category_id'    => 3,
                'description'    => 'Beras Ketan Putih berkualitas, cocok untuk lemper, lupis, dan kue tradisional.',
                'price'          => 600000,
                'weight_kg'      => 25,
                'stock'          => 75,
                'min_order'      => 1,
                'max_order'      => 20,
                'total_sold'     => 0,
                'avg_rating'     => 4.7,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('ketan-SI.png'),
            ],

            // ── MEDIUM (category_id: 2) ─────────────────────────────────────
            [
                'name'           => 'Beras Putih Cap Mangkok biru',
                'category_id'    => 2,
                'description'    => 'Beras dengan kualitas baik, cocok untuk konsumsi harian keluarga.',
                'price'          => 700000,
                'weight_kg'      => 50,
                'stock'          => 150,
                'min_order'      => 1,
                'max_order'      => 25,
                'total_sold'     => 0,
                'avg_rating'     => 4.5,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('mangkok-biru.png'),
            ],
            [
                'name'           => 'Beras Putih Cap Mangkok Merah',
                'category_id'    => 2,
                'description'    => 'Beras Putih Cap Mangkok Merah kualitas medium, nasi pulen dan tahan lama.',
                'price'          => 710000,
                'weight_kg'      => 50,
                'stock'          => 180,
                'min_order'      => 1,
                'max_order'      => 30,
                'total_sold'     => 0,
                'avg_rating'     => 4.4,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('mangkok.png'),
            ],
            [
                'name'           => 'Beras Cap Mulus Rahayu',
                'category_id'    => 2,
                'description'    => 'Beras Mulus Rahayu, cocok untuk kebutuhan rumah tangga sehari-hari.',
                'price'          => 695000,
                'weight_kg'      => 50,
                'stock'          => 160,
                'min_order'      => 1,
                'max_order'      => 25,
                'total_sold'     => 0,
                'avg_rating'     => 4.4,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('mr.png'),
            ],
            [
                'name'           => 'Beras Putih Kepala Putri  NR Merahnr',
                'category_id'    => 2,
                'description'    => 'Beras Putih Kepala Putri nr NR Merah kualitas medium butir panjang, bersih dan berkualitas untuk keluarga.',
                'price'          => 725000,
                'weight_kg'      => 50,
                'stock'          => 170,
                'min_order'      => 1,
                'max_order'      => 30,
                'total_sold'     => 0,
                'avg_rating'     => 4.3,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('nr-merah.png'),
            ],
            [
                'name'           => 'Beras Putih Slyp Pandan Medium',
                'category_id'    => 2,
                'description'    => 'Beras slyp dengan aroma pandan ringan, harga ekonomis untuk keluarga besar.',
                'price'          => 600000,
                'weight_kg'      => 10,
                'stock'          => 210,
                'min_order'      => 2,
                'max_order'      => 50,
                'total_sold'     => 0,
                'avg_rating'     => 4.2,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('pandan-wangi.jpg'),
            ],

            // ── KETAN (category_id: 3) ──────────────────────────────────────
            [
                'name'           => 'Beras Merah Rojo Lele Pera Cap KM',
                'category_id'    => 2,
                'description'    => 'Beras pera untuk nasi goreng dan lontong.',
                'price'          => 850000,
                'weight_kg'      => 50,
                'stock'          => 80,
                'min_order'      => 1,
                'max_order'      => 15,
                'total_sold'     => 0,
                'avg_rating'     => 4.7,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('pera-KM.png'),
            ],
            [
                'name'           => 'Beras Pera SL',
                'category_id'    => 3,
                'description'    => 'Beras pera untuk nasi goreng dan lontong.',
                'price'          => 830000,
                'weight_kg'      => 50,
                'stock'          => 80,
                'min_order'      => 1,
                'max_order'      => 15,
                'total_sold'     => 0,
                'avg_rating'     => 4.7,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('pera-SL.png'),
            ],
            [
                'name'           => 'Beras CAP Putra Mandiri',
                'category_id'    => 3,
                'description'    => 'Beras pera untuk nasi goreng dan lontong.',
                'price'          => 685000,
                'weight_kg'      => 50,
                'stock'          => 80,
                'min_order'      => 1,
                'max_order'      => 15,
                'total_sold'     => 0,
                'avg_rating'     => 4.7,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('pm.png'),
            ],
            [
                'name'           => 'Beras Cap Rajawali',
                'category_id'    => 3,
                'description'    => 'Beras putih berkualitas, cocok untuk lemper, lupis, dan kue tradisional.',
                'price'          => 670000,
                'weight_kg'      => 50,
                'stock'          => 70,
                'min_order'      => 1,
                'max_order'      => 15,
                'total_sold'     => 0,
                'avg_rating'     => 4.8,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('rajawali.png'),
            ],
            [
                'name'           => 'Beras Ketan Ramos BMW',
                'category_id'    => 3,
                'description'    => 'Beras ketan berkualitas tinggi, cocok untuk bubur ketan hitam dan minuman.',
                'price'          => 300000,
                'weight_kg'      => 25,
                'stock'          => 50,
                'min_order'      => 1,
                'max_order'      => 10,
                'total_sold'     => 0,
                'avg_rating'     => 4.9,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('ramos-bmw.jpg'),
            ],
            [
                'name'           => 'Beras Cap RR',
                'category_id'    => 1,
                'description'    => 'Beras Putih berkualitas tinggi, cocok untuk konsumsi sehari-hari.',
                'price'          => 680000,
                'weight_kg'      => 50,
                'stock'          => 60,
                'min_order'      => 1,
                'max_order'      => 10,
                'total_sold'     => 0,
                'avg_rating'     => 4.8,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('rr.png'),
            ],
            [
                'name'           => 'Beras Cap RY Merah',
                'category_id'    => 3,
                'description'    => 'Beras beras merah berkualitas, cocok untuk konsumsi sehat dan diet.',
                'price'          => 665000,
                'weight_kg'      => 50,
                'stock'          => 55,
                'min_order'      => 1,
                'max_order'      => 10,
                'total_sold'     => 0,
                'avg_rating'     => 4.6,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('ry-merah.png'),
            ],

            // ── EKONOMI (category_id: 4) ────────────────────────────────────
            [
                'name'           => 'Beras Putih SJ Segitiga',
                'category_id'    => 2,
                'description'    => 'Beras Putih berkualitas medium, cocok untuk konsumsi sehari-hari.',
                'price'          => 670000,
                'weight_kg'      => 50,
                'stock'          => 500,
                'min_order'      => 5,
                'max_order'      => 100,
                'total_sold'     => 0,
                'avg_rating'     => 4.0,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('sj-segitiga.png'),
            ],
            [
                'name'           => 'Beras Putih CAP SL',
                'category_id'    => 2,
                'description'    => 'Beras Putih berkualitas tinggi, cocok untuk konsumsi sehari-hari.',
                'price'          => 715000,
                'weight_kg'      => 50,
                'stock'          => 300,
                'min_order'      => 1,
                'max_order'      => 50,
                'total_sold'     => 0,
                'avg_rating'     => 4.1,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('SL.png'),
            ],
            [
                'name'           => 'Beras Putih Cap SMJ',
                'category_id'    => 2,
                'description'    => 'Beras Putih berkualitas tinggi, cocok untuk konsumsi sehari-hari.',
                'price'          => 690000,
                'weight_kg'      => 50,
                'stock'          => 400,
                'min_order'      => 2,
                'max_order'      => 80,
                'total_sold'     => 0,
                'avg_rating'     => 4.0,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('smj.png'),
            ],
            [
                'name'           => 'Beras Putih Cap SP',
                'category_id'    => 2,
                'description'    => 'Beras Putih berkualitas tinggi, cocok untuk konsumsi sehari-hari.',
                'price'          => 680000,
                'weight_kg'      => 50,
                'stock'          => 100,
                'min_order'      => 1,
                'max_order'      => 20,
                'total_sold'     => 0,
                'avg_rating'     => 4.2,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('sp.png'),
            ],
            [
                'name'           => 'Beras Putih Cap SR',
                'category_id'    => 3,
                'description'    => 'Beras Putih berkualitas tinggi, cocok untuk konsumsi sehari-hari.',
                'price'          => 700000,
                'weight_kg'      => 50,
                'stock'          => 350,
                'min_order'      => 1,
                'max_order'      => 50,
                'total_sold'     => 0,
                'avg_rating'     => 4.1,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('sr.png'),
            ],
        ];

        foreach ($products as $product) {
            DB::table('products')->insert(array_merge($product, [
                'slug'       => Str::slug($product['name']) . '-' . uniqid(),
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }

    private function getImage(string $filename): string
    {
        return 'products/' . $filename;
    }
}
