<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ── PREMIUM (category_id: 1) ────────────────────────────────────
            [
                'name'           => 'Beras Putih AJP',
                'category_id'    => 1,
                'description'    => 'Beras berkualitas tinggi dengan tekstur pulen dan aroma wangi alami.',
                'price'          => 660000,
                'weight_kg'      => 50,
                'stock'          => 120,
                'min_order'      => 1,
                'max_order'      => 20,
                'total_sold'     => 50,
                'avg_rating'     => 4.8,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('ajp.png'),
            ],
            [
                'name'           => 'Beras Putih Bima',
                'category_id'    => 1,
                'description'    => 'Beras premium asal Jawa Tengah, butir panjang dengan aroma wangi khas.',
                'price'          => 675000,
                'weight_kg'      => 10,
                'stock'          => 90,
                'min_order'      => 1,
                'max_order'      => 20,
                'total_sold'     => 75,
                'avg_rating'     => 4.9,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('bima.png'),
            ],
            [
                'name'           => 'Beras Putih Cap BK ',
                'category_id'    => 1,
                'description'    => 'Beras cap bk , tekstur nasi lembut dan harum.',
                'price'          => 670000,
                'weight_kg'      => 10,
                'stock'          => 60,
                'min_order'      => 1,
                'max_order'      => 15,
                'total_sold'     => 110,
                'avg_rating'     => 4.9,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('bk-kupu-kupu.png'),
            ],
            [
                'name'           => 'Beras Putih Cap Bunga Mawae',
                'category_id'    => 1,
                'description'    => 'Beras tanpa pestisida, ditanam secara alami.',
                'price'          => 360000,
                'weight_kg'      => 25,
                'stock'          => 40,
                'min_order'      => 1,
                'max_order'      => 10,
                'total_sold'     => 60,
                'avg_rating'     => 5.0,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('bunga.png'),
            ],
            [
                'name'           => 'Beras ketan Putih cap mikkymouse ',
                'category_id'    => 3,
                'description'    => 'ketan premium putih',
                'price'          => 550000,
                'weight_kg'      => 25,
                'stock'          => 200,
                'min_order'      => 1,
                'max_order'      => 30,
                'total_sold'     => 200,
                'avg_rating'     => 4.6,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('Ketan-mikkymouse.png'),
            ],
            [
                'name'           => 'Beras ketan  Putih Cap SI ',
                'category_id'    => 1,
                'description'    => 'Ketan putih berkualitas, cocok untuk lemper, lupis, dan kue tradisional.',
                'price'          => 600000,
                'weight_kg'      => 25,
                'stock'          => 75,
                'min_order'      => 1,
                'max_order'      => 20,
                'total_sold'     => 85,
                'avg_rating'     => 4.7,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('ketan-SI.png'),
            ],

            // ── MEDIUM (category_id: 2) ─────────────────────────────────────
            [
                'name'           => 'Beras Putih Cap Mangkok biru',
                'category_id'    => 2,
                'description'    => 'Beras dengan kualitas baik, cocok untuk konsumsi harian keluarga.',
                'price'          => 700000,
                'weight_kg'      => 50,
                'stock'          => 150,
                'min_order'      => 1,
                'max_order'      => 25,
                'total_sold'     => 30,
                'avg_rating'     => 4.5,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('mangkok-biru.png'),
            ],
            [
                'name'           => 'Beras Putih Cap Mangkok Merah',
                'category_id'    => 2,
                'description'    => 'Beras setra ramos kualitas medium, nasi pulen dan tahan lama.',
                'price'          => 710000,
                'weight_kg'      => 50,
                'stock'          => 180,
                'min_order'      => 1,
                'max_order'      => 30,
                'total_sold'     => 95,
                'avg_rating'     => 4.4,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('mangkok.png'),
            ],
            [
                'name'           => 'Beras Putih Bengawan Solo',
                'category_id'    => 2,
                'description'    => 'Beras kualitas medium dari Jawa Tengah, harga terjangkau dan rasanya enak.',
                'price'          => 355000,
                'weight_kg'      => 25,
                'stock'          => 200,
                'min_order'      => 2,
                'max_order'      => 50,
                'total_sold'     => 140,
                'avg_rating'     => 4.3,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('bengawan-solo.jpg'),
            ],
            [
                'name'           => 'Beras Putih Rojolele Makmur MR',
                'category_id'    => 2,
                'description'    => 'Beras rojolele pilihan, cocok untuk kebutuhan rumah tangga sehari-hari.',
                'price'          => 695000,
                'weight_kg'      => 50,
                'stock'          => 160,
                'min_order'      => 1,
                'max_order'      => 25,
                'total_sold'     => 70,
                'avg_rating'     => 4.4,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('rojolele-makmur.jpg'),
            ],
            [
                'name'           => 'Beras Putih Kepala Putri nr merah',
                'category_id'    => 2,
                'description'    => 'Beras medium butir panjang, bersih dan berkualitas untuk keluarga.',
                'price'          => 7250000,
                'weight_kg'      => 50,
                'stock'          => 170,
                'min_order'      => 1,
                'max_order'      => 30,
                'total_sold'     => 55,
                'avg_rating'     => 4.3,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('kepala-putri.jpg'),
            ],
            [
                'name'           => 'Beras Putih Slyp Pandan Medium',
                'category_id'    => 2,
                'description'    => 'Beras slyp dengan aroma pandan ringan, harga ekonomis untuk keluarga besar.',
                'price'          => 150000,
                'weight_kg'      => 10,
                'stock'          => 210,
                'min_order'      => 2,
                'max_order'      => 50,
                'total_sold'     => 120,
                'avg_rating'     => 4.2,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('pandan-wangi.jpg'),
            ],

            // ── KETAN (category_id: 3) ──────────────────────────────────────
            [
                'name'           => 'Beras Merah Rojo Lele pera km',
                'category_id'    => 3,
                'description'    => 'Beras pera untuk nasi goreng dan lontong.',
                'price'          => 8500000,
                'weight_kg'      => 50,
                'stock'          => 80,
                'min_order'      => 1,
                'max_order'      => 15,
                'total_sold'     => 20,
                'avg_rating'     => 4.7,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('pera-KM.png'),
            ],
            [
                'name'           => 'Beras Mawar Ramos BMW Pandan Wangi pera sl',
                'category_id'    => 3,
                'description'    => 'Beras putih berkualitas, cocok untuk makanan tradisional dan kue.',
                'price'          => 830000,
                'weight_kg'      => 50,
                'stock'          => 80,
                'min_order'      => 1,
                'max_order'      => 15,
                'total_sold'     => 20,
                'avg_rating'     => 4.7,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('mawar-ramos.jpg'),
            ],
            [
                'name'           => 'Beras pm',
                'category_id'    => 3,
                'description'    => 'Beras putih berkualitas, cocok untuk makanan tradisional dan kue.',
                'price'          => 685000,
                'weight_kg'      => 50,
                'stock'          => 80,
                'min_order'      => 1,
                'max_order'      => 15,
                'total_sold'     => 20,
                'avg_rating'     => 4.7,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('pandan-wangi.jpg'),
            ],
            [
                'name'           => 'Beras rajawali',
                'category_id'    => 3,
                'description'    => 'Ketan putih berkualitas, cocok untuk lemper, lupis, dan kue tradisional.',
                'price'          => 670000,
                'weight_kg'      => 50,
                'stock'          => 70,
                'min_order'      => 1,
                'max_order'      => 15,
                'total_sold'     => 35,
                'avg_rating'     => 4.8,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('ketan-putih-super.jpg'),
            ],
            [
                'name'           => 'Beras Ketan ramos-bmw',
                'category_id'    => 3,
                'description'    => 'ramos bmw, cocok untuk bubur ketan hitam dan minuman.',
                'price'          => 300000,
                'weight_kg'      => 25,
                'stock'          => 50,
                'min_order'      => 1,
                'max_order'      => 10,
                'total_sold'     => 28,
                'avg_rating'     => 4.9,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('ketan-hitam-organik.jpg'),
            ],
            [
                'name'           => 'Beras cap rr',
                'category_id'    => 3,
                'description'    => 'Beras merah organik dari lahan pegunungan, bebas bahan kimia dan kaya nutrisi.',
                'price'          => 680000,
                'weight_kg'      => 50,
                'stock'          => 60,
                'min_order'      => 1,
                'max_order'      => 10,
                'total_sold'     => 40,
                'avg_rating'     => 4.8,
                'is_active'      => 1,
                'is_recommended' => 1,
                'image'          => $this->getImage('merah-organik-gunung.jpg'),
            ],
            [
                'name'           => 'Beras cap ry-merah',
                'category_id'    => 3,
                'description'    => 'Beras hitam pilihan dari Jawa, kaya serat dan sangat cocok untuk diet sehat.',
                'price'          => 665000,
                'weight_kg'      => 50,
                'stock'          => 55,
                'min_order'      => 1,
                'max_order'      => 10,
                'total_sold'     => 18,
                'avg_rating'     => 4.6,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('hitam-jawa-super.jpg'),
            ],

            // ── EKONOMI (category_id: 4) ────────────────────────────────────
            [
                'name'           => 'Beras Putih cap sj segitiga',
                'category_id'    => 3,
                'description'    => 'Beras IR64 harga terjangkau untuk kebutuhan sehari-hari skala besar.',
                'price'          => 670000,
                'weight_kg'      => 50,
                'stock'          => 500,
                'min_order'      => 5,
                'max_order'      => 100,
                'total_sold'     => 450,
                'avg_rating'     => 4.0,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('ir64-ekonomi.jpg'),
            ],
            [
                'name'           => 'Beras Putih Sl',
                'category_id'    => 3,
                'description'    => 'Beras slyp curah ekonomis 25 kg, cocok untuk usaha warung dan catering.',
                'price'          => 715000,
                'weight_kg'      => 50,
                'stock'          => 300,
                'min_order'      => 1,
                'max_order'      => 50,
                'total_sold'     => 280,
                'avg_rating'     => 4.1,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('slyp-ekonomi-25kg.jpg'),
            ],
            [
                'name'           => 'Beras Putih cap smj',
                'category_id'    => 3,
                'description'    => 'Beras rojolele harga ekonomis, cocok untuk konsumsi keluarga banyak anggota.',
                'price'          => 690000,
                'weight_kg'      => 50,
                'stock'          => 400,
                'min_order'      => 2,
                'max_order'      => 80,
                'total_sold'     => 310,
                'avg_rating'     => 4.0,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('rojolele-ekonomi.jpg'),
            ],
            [
                'name'           => 'Beras Putih cap sp',
                'category_id'    => 3,
                'description'    => 'Beras setra curah harga hemat, ideal untuk pembelian dalam jumlah besar.',
                'price'          => 680000,
                'weight_kg'      => 50,
                'stock'          => 100,
                'min_order'      => 1,
                'max_order'      => 20,
                'total_sold'     => 90,
                'avg_rating'     => 4.2,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('setra-ekonomi-bulk.jpg'),
            ],
            [
                'name'           => 'Beras Putih cap sr',
                'category_id'    => 3,
                'description'    => 'Beras kepala ekonomi kemasan 5 kg, pas untuk keluarga kecil.',
                'price'          => 700000,
                'weight_kg'      => 50,
                'stock'          => 350,
                'min_order'      => 1,
                'max_order'      => 50,
                'total_sold'     => 220,
                'avg_rating'     => 4.1,
                'is_active'      => 1,
                'is_recommended' => 0,
                'image'          => $this->getImage('kepala-ekonomi-5kg.jpg'),
            ],
        ];

        foreach ($products as $product) {
            DB::table('products')->insert(array_merge($product, [
                'slug'       => Str::slug($product['name']) . '-' . uniqid(),
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }

    private function getImage(string $filename): string
    {
        return 'products/' . $filename;
    }
}